add_rules("mode.debug", "mode.release")
add_rules("plugin.vsxmake.autoupdate")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

rule("CompilerFlags")
    on_load(function (target)
        target:add("cxxflags", "gcc::-Wno-changes-meaning")
        target:add("cxxflags", "clag::-Wno-changes-meaning")

        target:add("cxxflags", "cl::/EHsc")
        target:add("cxxflags", "cl::/permissive-")
        target:add("cxxflags", "cl::/wd4514 /wd4820")
    end)
rule_end()

includes("Vendor.lua")
includes("HeaderTool/HeaderTool.lua")
includes("Engin5/Engin5.lua")
includes("Editor/Editor.lua")
includes("Sandbox/Sandbox.lua")